"""
Configuration module for the ACE UPV Article Grader.

This module loads configuration from environment variables.

Environment Variables:
    Optional:
        - OPIK_PROJECT_NAME: Opik project name for tracking
        - LOG_DIR: Directory for logs (default: "logs")
        - OPIK_WORKSPACE: Opik workspace name (default: "default")
        - EPOCHS: Number of adaptation epochs (default: 3)
        - CHECKPOINT_ENABLED: Enable checkpoint/resume (default: true)
        - DEBUG_ADAPT: Enable debug logging (default: false)
        - ENABLE_BASELINE_LOGGING: Log baseline results (default: false)
        - VIZ_FORMAT: Figure format for visualizations (default: "png")
        - SHOULD_SAVE_FIGS: Enable to save figures generated by the `viz.py` program

Example .env file:
    # AI MODEL API KEYS.
    GOOGLE_API_KEY=***

    # OPIK TRACKING.
    OPIK_PROJECT_NAME=
    COMET_API_KEY=
    OPIK_TRACK_DISABLE=True

    # CONFIGURATION
    VIZ_FORMAT=png

    # PROJECT DIRECTORIES.
    ACE_PARSE_DIR=./parse
    ACE_LOG_DIR=./logs
    ACE_EPOCHS_DIR=./logs/epochs

    # PROJECT FILES.
    ACE_RUBRIC_FILE=parse/internship.enhance_b2_article_writing_rubric_structured.pdf
    ACE_EXAMPLES_FILE=parse/debug_batch_4_examples.pdf
"""

import os
import sys
from pathlib import Path
from typing import List, Optional, Final
from dataclasses import dataclass, field
from dotenv import load_dotenv

load_dotenv()

# === PATH CONFIGURATION ===

BASE_DIR = Path(".").resolve()
"""Base directory of the project (current working directory)."""

PARSE_DIR = Path(os.getenv("ACE_PARSE_DIR", BASE_DIR / "parse")).resolve()
"""Directory where the parsed PDFs are stored (rubric, examples)"""

LOG_DIR = Path(os.getenv("ACE_LOG_DIR", BASE_DIR / "logs")).resolve()
"""Directory where logs and checkpoints are stored."""

EPOCHS_DIR = Path(os.getenv("ACE_EPOCHS_DIR", LOG_DIR / "epochs")).resolve()
"""Directory containing per-epoch JSON filed under logs (used by adapt.py)."""

# Ensure the core directories exist.
LOG_DIR.mkdir(parents=True, exist_ok=True)
EPOCHS_DIR.mkdir(parents=True, exist_ok=True)

# === OPIK CONFIGURATION ===
OPIK_PROJECT_NAME = os.getenv("OPIK_PROJECT_NAME")
"""
The Opik project name for program execution trace logging.\n
Must set in .env file 
"""

# === ADAPTATION PARAMETERS === 
EPOCHS = 3
"""Number of Epochs for the adaptation process."""

DEBUG_ADAPT = False
"""Whether debug conditionals in the `adapt.py` file should execute."""

# === CHECKPOINT CONFIGURATION ===
CHECKPOINT_ENABLED = True
"""Determines whether the `adapt.py` file should execute in checkpoint mode."""

CHECKPOINT_PATH = LOG_DIR / "adaptation_checkpoint.json"
"""File path where the adaptation checkpoint is stored."""

# === PRUNING CONFIGURATION ===

PRUNING_ENABLED = os.getenv("PRUNING_ENABLED", "True").lower() == "true"
"""Enable playbook pruning during adaptation."""

PRUNING_STRATEGY = os.getenv("PRUNING_STRATEGY", "hybrid")
"""
Pruning Strategy: 'similarity', 'usage', 'performance', 'age', or 'hybrid'.

- similarity: Remove semantically duplicate bullets using cosine similarity
- usage: Remove bullets rarely referenced in bullet_ids
- performance: Remove bullets not correlated with score improvements
- age: Remove bullets unused for N epochs
- hybrid: Combine multiple strategies (recommended)
"""

PRUNING_SIMILARITY_THRESHOLD = float(os.getenv("PRUNING_SIMILARITY_THRESHOLD", "0.85"))
"""Cosine similarity threshold for duplicate detection (0.0-1.0). Default: 0.85"""

PRUNING_MIN_USAGE_COUNT = int(os.getenv("PRUNING_MIN_USAGE_COUNT", "2"))
"""Minimum times a bullet must be used to avoid pruning. Default: 2"""

PRUNING_MIN_PLAYBOOK_SIZE = int(os.getenv("PRUNING_MIN_PLAYBOOK_SIZE", "10"))
"""Minimum playbook size before playbook can be pruned. Default: 10"""

PRUNING_AGE_THRESHOLD_EPOCHS = int(os.getenv("PRUNING_AGE_THRESHOLD_EPOCHS", "3"))
"""Remove bullets unused for this many epochs. Default: 3"""

PRUNING_MAX_REMOVE_PER_EPOCH = int(os.getenv("PRUNING_MAX_REMOVE_PER_EPOCH", "5"))
"""Maximum bullets to remove per pruning operation. Default: 5"""

PRUNING_DRY_RUN = os.getenv("PRUNING_DRY_RUN", "False").lower() == "true"
"""If True, log pruning decisions but don't modify playbook. Default: False"""

PRUNING_LOG_FILE = LOG_DIR / "pruning_log.json"
"""File where pruning operations are logged."""

PRUNING_METADATA_FILE = LOG_DIR / "bullet_metadata.json"
"""File where bullet metadata is stored."""

USAGE_LOG_FILE = LOG_DIR / "usage_log.json"
"""File where bullet usage is tracked."""

USAGE_STATS_FILE = LOG_DIR / "usage_stats.json"
"""File where bullet usage statistics are stored."""

# === OTHER CONFIGURATION ===
SHOULD_SAVE_FIGS = False
"""Determines whether figures generated by the visualization program are saved."""

VIZ_FORMAT = os.getenv("VIZ_FORMAT")
"""File format for the images saved by the visualization program."""

# === FILES ===
RUBRIC_FILE = os.getenv("ACE_RUBRIC_FILE", PARSE_DIR / "internship.enhance_b2_article_writing_rubric_structured.pdf")

# Student examples PDF.
EXAMPLES_FILE = os.getenv("ACE_EXAMPLES_FILE", PARSE_DIR / "internship.b2_writing_examples_scores.pdf")

# JSON summarising adaptation loop.
ADAPTATION_SUMMARY_FILE = LOG_DIR / "adaptation_summary.json"

# Latest playbook file.
LATEST_PLAYBOOK_FILE = LOG_DIR / "latest_playbook.json"

# Parsing debug log.
PARSE_DEBUG_LOG = LOG_DIR / "parse_debug.log"

# Grade logs.
GRADES_LOG_FILE = LOG_DIR / "grades.log"

# Epoch failure log for adaptatio.
EPOCH_FAILURE_LOG = LOG_DIR / "epoch_failure.log"

# JSON failures from ACE roles.
JSON_FAILURE_LOG = LOG_DIR / "json_failures.log"


TASK_PROMPT = """
You have just seen the following advertisement in the university magazine:
Share with us what you think about the importance of physically attending classes in-person for university students instead of online classes. We're looking for articles about the benefits of studying in a classroom with a teacher. The best article will be published in our university magazine and the winner will receive a €200 gift card.
You have decided to contribute, Write an ARTICLE in which you:
• explain why physically attending classes can improve learning.
• mention why attending class at a university also provides the student with other
resources and facilities.
• suggest ways in which teachers can encourage students to go to class.
Give your article a title. Write your ARTICLE in 180-220 words.
"""
"""The task prompt used by the ACE roles in the adaptation process"""

SEED_BULLETS = [
    "OUTPUT FORMAT: Respond with a raw JSON object ONLY: {\"reasoning\": \"...\", \"bullet_ids\": [...], \"final_answer\": \"RESULTS,TA:X.0,CC:X.0,GR:X.0,LR:X.0,OWP:X.0\"}. NO Markdown fences (```json), NO extra text, NO explanations outside JSON.",
    "CRITICAL: In 'final_answer', use EXACTLY: RESULTS,TA:X.0,CC:X.0,GR:X.0,LR:X.0,OWP:X.0 at end. Ensure a valid and parseable JSON overall.",
    "JSON RULES: Use \\n for line breaks in 'reasoning'. Escape quotes properly. No apostrophes in strings.",
    "CHAIN OF THOUGHT: 1. Quote evidence. 2. Map to rubric level. 3. Justify score. Put in 'reasoning'.",
    "DETERMINISM: Stick to rubric descriptors verbatim.",
    "RUBRIC BULLETS: Use these for grading.", # rubric_bullets will be added dynamically.
]
"""Seed bullets used for a fresh Playbook initiation."""

# === CONFIGURATION VALIDATION ===

@dataclass
class ConfigValidationError:
    """Represents a configuration validaton error."""
    key: str
    value: Optional[str]
    error: str
    severity: str

class ConfigValidator:
    """Validates configuration and provides helpful error messages."""

    def __init__(self):
        self.errors: List[ConfigValidationError] = []
        self.warnings: List[ConfigValidationError] = []

    def validate_required_string(self, key: str, value: Optional[str], description: str = ""):
        """Validate that a required string is present and non-empty."""
        if value is None or not value.strip():
            self.errors.append(ConfigValidationError(
                key=key,
                value=value,
                error=f"Required configuration missing: {key}. {description}",
                severity='error'
            ))
            return False
        return True
    
    def validate_path_exists(self, key: str, path: Path, description: str = ""):
        """Validate that a path exists."""
        if not path.exists():
            self.warnings.append(ConfigValidationError(
                key=key,
                value=str(path),
                error=f"Path does not exist: {path}. {description}",
                severity='warning'
            ))
            return False
        return True
    
    def validate_directory_writable(self, key: str, directory: Path):
        """Validate that a directory is writable."""
        try:
            directory.mkdir(parents=True, exist_ok=True)
            test_file = directory / ".write_test"
            test_file.touch()
            test_file.unlink()
            return True
        except Exception as e:
            self.errors.append(ConfigValidationError(
                key=key,
                value=str(directory),
                error=f"Directory not writable: {directory}. Error: {e}",
                severity='error'
            ))
            return False
        
    def validate_int_range(self, key: str, value: int, min_val: int, max_val: int):
        """Validate that an integer is within a valid range."""
        if not (min_val <= value <= max_val):
            self.errors.append(ConfigValidationError(
                key=key,
                value=str(value),
                error=f"{key}={value} out of valid range [{min_val}, {max_val}]",
                severity='error'
            ))
            return False
        return True
    
    def print_summary(self):
        """Print validation summary."""
        if not self.errors and not self.warnings:
            print("✅ Configuration validation passed")
            return True
        
        if self.warnings:
            print(f"\n⚠️ Configuration Warnings ({len(self.warnings)}):")
            for warning in self.warnings:
                print(f"        • {warning.key}: {warning.error}")

        if self.errors:
            print(f"\n❌ Configuration Errors ({len(self.errors)}):")
            for error in self.errors:
                print(f"        • {error.key}: {error.error}")

            print("\n💡 How to fix:")
            print("     1. Ensure constants are configured correctly")
            print("     2. Create a .env file in the project root")
            print("     3. Add the required configuration")
            print("     4. See .env.example for a complete template")
            
            return False
        return True
    
    def validate_configuration() -> bool:
        """
        Validate all configuration settings.

        Returns:
            bool: True if configuration is valid, False otherwise

        Raises:
            SystemExit: If critical configuration errors are found
        """
        validator = ConfigValidator()

        # === REQUIRED SETTINGS ===
        validator.validate_required_string(
            "VIZ_FORMAT",
            VIZ_FORMAT,
            "This is required to save figures generated by the `viz.py` file. Please set it in the .env file."
        )

        validator.validate_required_string(
            "ACE_RUBRIC_FILE",
            RUBRIC_FILE,
            "This is necessary to execute the adaptation program."
        )

        validator.validate_required_string(
            "ACE_EXAMPLES_FILE",
            EXAMPLES_FILE,
            "This is necessary to execute the adaptation program."
        )

        # === PATH VALIDATION ===
        validator.validate_path_exists(
            "LOG_DIR",
            LOG_DIR,
            "Ensure Log directory has been created"
        )

        validator.validate_path_exists(
            "EPOCHS_DIR",
            EPOCHS_DIR,
            "Ensure the Epochs directory has been created."
        )

        validator.validate_directory_writable("LOG_DIR", LOG_DIR)

        # === PARAMETER VALIDATION ===
        validator.validate_int_range("EPOCHS", EPOCHS, 1, 999)

        # === PRINT SUMMARY ===
        is_valid = validator.print_summary()

        if not is_valid:
            print("\n❌ Configuration validation failed. Please fix the errors above.")
            print("     Application cannot start with invalid configuration.")
            sys.exit(1)

        return True
    

if __name__ != "__main__":
    # Only validate when imported (not when running this file directly)
    try:
        validator = ConfigValidator
        validator.validate_configuration()
    except SystemExit:
        # Re-raise to stop application startup
        raise
    except Exception as e:
        print(f"❌ Unexpected error during configuration validation: {e}")
        sys.exit(1)

if __name__ == "__main__":
    """
    Run this file directly to validate configuration:

        `python constants.py`
    """

    print("=" * 70)
    print("CONFIGURATION VALIDATION TEST")
    print("=" * 70)
    print()

    # Test validation.
    is_valid = ConfigValidator.validate_configuration()

    if is_valid:
        print("\n" + "=" * 70)
        print("CONIGURATION IS VALID")
        print("=" * 70)